# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ChessMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 803)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 803))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 803))
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setMouseTracking(True)
        self.ChessView = QtWidgets.QGraphicsView(self.centralwidget)
        self.ChessView.setGeometry(QtCore.QRect(1, 1, 802, 802))
        self.ChessView.setObjectName("ChessView")
        self.ChessView.setMouseTracking(True)
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(860, 600, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.StartButton.setFont(font)
        self.StartButton.setAutoFillBackground(False)
        self.StartButton.setObjectName("StartButton")
        self.FailButton = QtWidgets.QPushButton(self.centralwidget)
        self.FailButton.setGeometry(QtCore.QRect(860, 670, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FailButton.setFont(font)
        self.FailButton.setAutoFillBackground(False)
        self.FailButton.setObjectName("FailButton")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(860, 740, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ExitButton.setFont(font)
        self.ExitButton.setAutoFillBackground(False)
        self.ExitButton.setObjectName("ExitButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(820, 20, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(820, 70, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TimeLabel.setStyleSheet("")
        self.TimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeLabel.setObjectName("TimeLabel")
        self.ResultLabel = QtWidgets.QLabel(self.centralwidget)
        self.ResultLabel.setGeometry(QtCore.QRect(820, 450, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.ResultLabel.setFont(font)
        self.ResultLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ResultLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.ResultLabel.setText("")
        self.ResultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultLabel.setObjectName("ResultLabel")
        self.tmpLabel = QtWidgets.QLabel(self.centralwidget)
        self.tmpLabel.setGeometry(QtCore.QRect(820, 380, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.tmpLabel.setFont(font)
        self.tmpLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tmpLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.tmpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tmpLabel.setObjectName("tmpLabel")
        self.ActionLabel = QtWidgets.QLabel(self.centralwidget)
        self.ActionLabel.setGeometry(QtCore.QRect(820, 160, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.ActionLabel.setFont(font)
        self.ActionLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ActionLabel.setStyleSheet("")
        self.ActionLabel.setText("")
        self.ActionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ActionLabel.setObjectName("ActionLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(860, 230, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(860, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.BlackNums = QtWidgets.QLabel(self.centralwidget)
        self.BlackNums.setGeometry(QtCore.QRect(930, 230, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.BlackNums.setFont(font)
        self.BlackNums.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BlackNums.setStyleSheet("")
        self.BlackNums.setText("")
        self.BlackNums.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.BlackNums.setObjectName("BlackNums")
        self.WhiteNums = QtWidgets.QLabel(self.centralwidget)
        self.WhiteNums.setGeometry(QtCore.QRect(930, 300, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.WhiteNums.setFont(font)
        self.WhiteNums.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.WhiteNums.setStyleSheet("")
        self.WhiteNums.setText("")
        self.WhiteNums.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.WhiteNums.setObjectName("WhiteNums")
        self.ChooseBlack = QtWidgets.QRadioButton(self.centralwidget)
        self.ChooseBlack.setGeometry(QtCore.QRect(880, 530, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ChooseBlack.setFont(font)
        self.ChooseBlack.setObjectName("ChooseBlack")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI五子棋"))
        self.StartButton.setText(_translate("MainWindow", "开始"))
        self.FailButton.setText(_translate("MainWindow", "认输"))
        self.ExitButton.setText(_translate("MainWindow", "退出"))
        self.label.setText(_translate("MainWindow", "TIME"))
        self.TimeLabel.setText(_translate("MainWindow", "00:00"))
        self.tmpLabel.setText(_translate("MainWindow", "比赛结果:"))
        self.label_3.setText(_translate("MainWindow", "黑子："))
        self.label_4.setText(_translate("MainWindow", "白子："))
        self.ChooseBlack.setText(_translate("MainWindow", "执黑先行"))

