# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ChessMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 803)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 803))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 803))
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setMouseTracking(True)
        self.chessView = QtWidgets.QGraphicsView(self.centralwidget)
        self.chessView.setGeometry(QtCore.QRect(1, 1, 802, 802))
        self.chessView.setObjectName("chessView")
        self.chessView.setMouseTracking(True)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(860, 600, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.startButton.setFont(font)
        self.startButton.setAutoFillBackground(False)
        self.startButton.setObjectName("startButton")
        self.failButton = QtWidgets.QPushButton(self.centralwidget)
        self.failButton.setGeometry(QtCore.QRect(860, 670, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.failButton.setFont(font)
        self.failButton.setAutoFillBackground(False)
        self.failButton.setObjectName("failButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(860, 740, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exitButton.setFont(font)
        self.exitButton.setAutoFillBackground(False)
        self.exitButton.setObjectName("exitButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(820, 20, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(820, 70, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeLabel.setStyleSheet("")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(820, 440, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resultLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.resultLabel.setText("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.tmpLabel = QtWidgets.QLabel(self.centralwidget)
        self.tmpLabel.setGeometry(QtCore.QRect(820, 370, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.tmpLabel.setFont(font)
        self.tmpLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tmpLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.tmpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tmpLabel.setObjectName("tmpLabel")
        self.actionLabel = QtWidgets.QLabel(self.centralwidget)
        self.actionLabel.setGeometry(QtCore.QRect(820, 140, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.actionLabel.setFont(font)
        self.actionLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.actionLabel.setStyleSheet("")
        self.actionLabel.setText("")
        self.actionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actionLabel.setObjectName("actionLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(860, 210, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(860, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.blackNums = QtWidgets.QLabel(self.centralwidget)
        self.blackNums.setGeometry(QtCore.QRect(930, 210, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.blackNums.setFont(font)
        self.blackNums.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.blackNums.setStyleSheet("")
        self.blackNums.setText("")
        self.blackNums.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.blackNums.setObjectName("blackNums")
        self.whiteNums = QtWidgets.QLabel(self.centralwidget)
        self.whiteNums.setGeometry(QtCore.QRect(930, 280, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.whiteNums.setFont(font)
        self.whiteNums.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.whiteNums.setStyleSheet("")
        self.whiteNums.setText("")
        self.whiteNums.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.whiteNums.setObjectName("whiteNums")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(840, 510, 181, 71))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setFlat(True)
        self.chooseBlack = QtWidgets.QRadioButton(self.groupBox)
        self.chooseBlack.setGeometry(QtCore.QRect(30, 20, 61, 31))
        self.chooseBlack.setObjectName("chooseBlack")
        self.chooseWhite = QtWidgets.QRadioButton(self.groupBox)
        self.chooseWhite.setGeometry(QtCore.QRect(110, 20, 61, 31))
        self.chooseWhite.setObjectName("chooseWhite")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI五子棋"))
        self.startButton.setText(_translate("MainWindow", "开始"))
        self.failButton.setText(_translate("MainWindow", "认输"))
        self.exitButton.setText(_translate("MainWindow", "退出"))
        self.label.setText(_translate("MainWindow", "五子棋"))
        self.timeLabel.setText(_translate("MainWindow", "算法试验"))
        self.tmpLabel.setText(_translate("MainWindow", "比赛结果"))
        self.label_3.setText(_translate("MainWindow", "黑: "))
        self.label_4.setText(_translate("MainWindow", "白: "))
        self.chooseBlack.setText(_translate("MainWindow", "黑"))
        self.chooseWhite.setText(_translate("MainWindow", "白"))

